version: '3'

services:
  db:
    image: your_database_image
    # configuration de la base de données

  web:
    build: .
    volumes:
      - ./django_chatbot/db.sqlite3:/app/db.sqlite3
    ports:
      - "8001:8001"

      - db
    command: sh -c "sleep 30 && python manage.py runserver"